import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-secondary-fixed-variant": "#92002a",
        "surface": "#fbf9f6",
        "surface-container": "#efeeeb",
        "background": "#fbf9f6",
        "on-error": "#ffffff",
        "surface-container-high": "#eae8e5",
        "surface-variant": "#e4e2df",
        "on-background": "#1b1c1a",
        "surface-container-low": "#f5f3f0",
        "outline": "#777584",
        "on-surface": "#1b1c1a",
        "primary": "#1f108e",
        "primary-fixed-dim": "#c3c0ff",
        "secondary-container": "#dc2c4f",
        "on-error-container": "#93000a",
        "secondary-fixed-dim": "#ffb2b7",
        "on-surface-variant": "#464553",
        "primary-fixed": "#e2dfff",
        "inverse-surface": "#30312f",
        "on-primary-fixed-variant": "#3b35a7",
        "surface-container-lowest": "#ffffff",
        "on-secondary": "#ffffff",
        "tertiary-container": "#004d34",
        "surface-dim": "#dbdad7",
        "inverse-primary": "#c3c0ff",
        "inverse-on-surface": "#f2f0ed",
        "error": "#ba1a1a",
        "surface-bright": "#fbf9f6",
        "on-tertiary": "#ffffff",
        "tertiary-fixed-dim": "#68dba9",
        "tertiary-fixed": "#85f8c4",
        "surface-tint": "#544fc0",
        "primary-container": "#3730a3",
        "on-primary": "#ffffff",
        "tertiary": "#003422",
        "surface-container-highest": "#e4e2df",
        "on-secondary-fixed": "#40000d",
        "on-tertiary-container": "#4ec493",
        "outline-variant": "#c8c4d5",
        "on-secondary-container": "#fffbff",
        "secondary-fixed": "#ffdadb",
        "error-container": "#ffdad6",
        "on-primary-fixed": "#0f0069",
        "on-tertiary-fixed": "#002114",
        "secondary": "#b90538",
        "on-primary-container": "#a9a7ff",
        "on-tertiary-fixed-variant": "#005137"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "space-xl": "2.5rem",
        "space-md": "1.25rem",
        "margin": "1.25rem",
        "space-xs": "0.375rem",
        "space-lg": "1.75rem",
        "space-sm": "0.75rem",
        "gutter": "1rem",
        "gutter-desktop": "1.5rem",
        "margin-desktop": "3rem"
      },
      fontFamily: {
        "label-sm": ["Plus Jakarta Sans"],
        "body-lg": ["Plus Jakarta Sans"],
        "headline-xl": ["Plus Jakarta Sans"],
        "headline-lg": ["Plus Jakarta Sans"],
        "label-lg": ["Plus Jakarta Sans"],
        "body-xl": ["Plus Jakarta Sans"],
        "headline-md": ["Plus Jakarta Sans"],
        "headline-lg-mobile": ["Plus Jakarta Sans"],
        "body-md": ["Plus Jakarta Sans"],
        "headline-xl-mobile": ["Plus Jakarta Sans"],
        "label-md": ["Plus Jakarta Sans"]
      },
      fontSize: {
        "label-sm": ["13px", { "lineHeight": "18px", "letterSpacing": "0.03em", "fontWeight": "600" }],
        "body-lg": ["18px", { "lineHeight": "28px", "letterSpacing": "0em", "fontWeight": "400" }],
        "headline-xl": ["40px", { "lineHeight": "52px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "headline-lg": ["32px", { "lineHeight": "42px", "letterSpacing": "-0.01em", "fontWeight": "700" }],
        "label-lg": ["16px", { "lineHeight": "24px", "letterSpacing": "0.01em", "fontWeight": "600" }],
        "body-xl": ["20px", { "lineHeight": "32px", "letterSpacing": "0em", "fontWeight": "500" }],
        "headline-md": ["22px", { "lineHeight": "32px", "letterSpacing": "0em", "fontWeight": "600" }],
        "headline-lg-mobile": ["24px", { "lineHeight": "34px", "letterSpacing": "0em", "fontWeight": "700" }],
        "body-md": ["16px", { "lineHeight": "26px", "letterSpacing": "0em", "fontWeight": "400" }],
        "headline-xl-mobile": ["30px", { "lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "700" }],
        "label-md": ["14px", { "lineHeight": "20px", "letterSpacing": "0.02em", "fontWeight": "600" }]
      }
    },
  },
  plugins: [],
};
export default config;
